In [1]:
# Data Processing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image

In [2]:
import pandas as pd


df = pd.read_csv('college.csv')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'college.csv'

In [ ]:
df.tail()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [ ]:
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_enc = LabelEncoder()

# Encode 'Placement' (Target variable)
data['Placement'] = label_enc.fit_transform(data['Placement'])

# Encode 'Internship_Experience' (Feature)
data['Internship_Experience'] = label_enc.fit_transform(data['Internship_Experience'])

NameError: name 'data' is not defined

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_enc = LabelEncoder()

# Encode 'Placement' (Target variable)
data['Placement'] = label_enc.fit_transform(data['Placement'])

# Encode 'Internship_Experience' (Feature)
data['Internship_Experience'] = label_enc.fit_transform(data['Internship_Experience'])

NameError: name 'data' is not defined